---
- name: Install Docker on Ubuntu 24.04
  hosts: pinky
  become: yes
  vars:
    username: hugo
    groupname: docker

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - gnupg2

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present

    - name: Update apt packages (again to refresh packages from Docker repository)
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Ensure the group exists
      group:
        name: "{{ groupname }}"
        state: present

    - name: Ensure the user exists
      user:
        name: "{{ username }}"
        state: present

    - name: Add the user to the group
      user:
        name: "{{ username }}"
        groups: "{{ groupname }}"
        append: yes