---
- name: Create Portainer volume
  hosts: all
  become: yes
  tasks:
    - name: Create Docker volume
      docker_volume:
        name: portainer_data

    - name: Pull Portainer Docker image
      docker_image:
        name: portainer/portainer-ce:latest
        state: present
        source: pull

    - name: Start Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
          - "9443:9443"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"