---
- name: Update APT and upgrade all packages
  hosts: ubuntu_servers
  become: yes

  tasks:
    - name: Update the APT package index
      apt:
        update_cache: yes

    - name: Upgrade all installed packages to their latest version
      apt:
        upgrade: dist
        autoclean: yes
        autoremove: yes

    # - name: Reboot the server if a kernel update was installed
    #   reboot:
    #     when: ansible_facts['pkg_mgr'] == 'apt'

